[phases.setup]
nixPkgs = ["tesseract4", "tesseract"]
aptPkgs = ["tesseract-ocr", "tesseract-ocr-eng"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-8000}"
